site_name: Narrowlink
site_url: https://docs.narrowlink.com/
repo_url: https://github.com/narrowlink/narrowlink
edit_uri: /narrowlink/docs/blob/main/docs/
repo_name: narrowlink
site_description: "Narrowlink is a versatile and powerful tool that facilitates high-performance NAT traversal, allowing you to publish TLS-secured web services to the internet, even when your server is 
behind a NAT network. It also enables you to share the network of a computer behind a NAT network with another computer that is also behind another NAT network"
copyright: 'Copyright &copy; 2023</div><div>Made with <a rel="nofollow external noreferrer" href="https://github.com/squidfunk/mkdocs-material/" target="_blank"
    rel="noopener">Material</a> for <a rel="nofollow external noreferrer" href="https://github.com/mkdocs/mkdocs/" target="_blank"
    rel="noopener">MkDocs</a>'
theme:
  name: material
  custom_dir: overrides
  logo: assets/NarrowLink-fff.svg
  favicon: assets/NarrowLink-888.svg
  icon:
    repo: fontawesome/brands/git-alt

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    - content.action.view
  prev_next_buttons_location: bottom
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/narrowlink
    - icon: fontawesome/brands/docker 
      link: https://hub.docker.com/r/narrowlink
  homepage: https://narrowlink.com
  generator: false
  meta_generator: false
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
    - search
    - redirects:
        redirect_maps:
            'index.md': 'getting-started/introduction.md'
nav:
  - Home: index.md
  - Getting started:
      [
        Introduction: getting-started/introduction.md,
        Architecture: getting-started/architecture.md,
        Installation: getting-started/installation.md,
        Use Cases: getting-started/use-cases.md,
      ]
  - Client: 
      [
        Introduction: client/introduction.md,
        Port Forwarding: client/port-forwarding.md,
        Proxy: client/proxy.md,
        Connect: client/connect.md,
      ]
  - Agent: agent/index.md
  - Gateway: gateway/index.md
