site_name: Narrowlink
site_url: https://docs.narrowlink.com/
repo_url: https://github.com/narrowlink/
edit_uri: /narrowlink/docs/blob/main/docs/
repo_name: narrowlink
copyright: Copyright &copy; 2023
theme:
  name: material
  custom_dir: overrides
  logo: assets/NarrowLink-fff.svg
  favicon: assets/NarrowLink-888.svg
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    - content.action.view
  prev_next_buttons_location: bottom
extra:
  homepage: https://narrowlink.com
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
    - search
    - redirects:
        redirect_maps:
            'index.md': 'getting-started/introduction.md'
nav:
  - Home: index.md
  - Getting started:
      [
        Introduction: getting-started/introduction.md,
        Architecture: getting-started/architecture.md,
        Installation: getting-started/installation.md,
        Use Cases: getting-started/use-cases.md,
      ]
  - Client: 
      [
        Introduction: client/introduction.md,
        Port Forwarding: client/port-forwarding.md,
        Proxy: client/proxy.md,
        Connect: client/connect.md,
      ]
  - Agent: agent/index.md
  - Gateway: gateway/index.md
